run:
  timeout: 5m
  go: "1.21"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - prealloc

linters-settings:
  goimports:
    local-prefixes: github.com/phongln/go-relay

issues:
  exclude-rules:
    - path: _test\.go
      linters: [errcheck]
